trigger:
  branches:
    include:
      - master
  paths:
    include:
      - BeginnerAppService

pool:
  vmImage: ubuntu-latest

variables:
- name: buildConfiguration
  value: 'Release'
- name: projectPath
  value: './BeginnerAppService/BeginnerAppService.csproj'

steps:
  - template: template-build.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      projectPath: $(projectPath)

  - task: DotNetCoreCLI@2
    displayName: '[.NET] Publish project'
    inputs:
      command: 'publish'
      projects: $(projectPath)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/BeginnerAppService'
      publishWebProjects: false
      zipAfterPublish: true

  - publish: '$(Build.ArtifactStagingDirectory)/BeginnerAppService/BeginnerAppService.zip'
    displayName: 'Publish artifact'
    artifact: webapp

    
  